# Generated by Django 4.2 on 2024-12-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='service',
            field=models.ManyToManyField(related_name='masters', to='beautyservice.service', verbose_name='Услуги мастера'),
        ),
        migrations.AlterField(
            model_name='master',
            name='salon',
            field=models.ManyToManyField(related_name='masters', to='beautyservice.salon', verbose_name='Салоны мастера'),
        ),
    ]
